# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CloudFormationCreateOrUpdateStack@1
  inputs:
        awsCredentials: 'newaws'
        regionName: 'us-east-1'
        stackName: 'jenkins'
        templateSource: 's3'
        s3BucketName: 'cf-templates-1sflxoazv6rb5-us-east-1'
        s3ObjectKey: '2019202gP1-template173aac9e5607'
        templateParametersSource: 'inline'
        templateParameters: |
          ConnectionLocation: '183.83.213.6/32'
          ImageId: 'ami-97785bed'
          KeyName: 'jenkins'
          OperatingSystem: 'amazonlinux'
          SecurityGroupPort: '22'

    


